from .branin import ParametrizedBranin
from .dixonprice import ParametrizedDixonPrice
from .beale import ParametrizedBeale
from .bukin import ParametrizedBukin
from .dropwave import ParametrizedDropwave
from .eggholder import ParametrizedEggholder
from .griewank import ParametrizedGriewank
from .holdertable import ParametrizedHoldertable
from .levy import ParametrizedLevy
from .rastrigin import ParametrizedRastrigin
from .rosenbrock import ParametrizedRosenbrock
from .sixhumpcamel import ParametrizedSixHumpCamel
from .styblinskitang import ParametrizedStyblinskiTang
from .threehumpcamel import ParametrizedThreeHumpCamel
